# Generated by Django 3.0.8 on 2020-11-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20201125_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
