# Generated by Django 3.0.8 on 2020-11-26 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20201126_0141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='first_name',
            new_name='default_first_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_name',
            new_name='default_last_name',
        ),
    ]
