# Generated by Django 3.0.8 on 2020-08-03 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='order_number',
            new_name='consultation_number',
        ),
    ]
