# Generated by Django 3.0.8 on 2020-08-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_consultation_consultation_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='consultation_idea',
            field=models.CharField(default='Please describe your project in as much detail as possible', max_length=3000),
        ),
    ]
