# Generated by Django 3.0.8 on 2020-10-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_consultation_consultation_idea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='consultation_idea',
            field=models.CharField(max_length=3000),
        ),
    ]
