# Generated by Django 3.0.8 on 2020-10-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_auto_20201006_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='email2',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
