# Generated by Django 3.0.8 on 2020-11-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0006_auto_20201008_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='consultation_idea',
            field=models.TextField(max_length=3000),
        ),
    ]
