# Generated by Django 3.0.8 on 2020-11-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0009_auto_20201111_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='email2',
        ),
    ]
