# Generated by Django 3.0.8 on 2020-11-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0010_remove_consultation_email2'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
