# Generated by Django 3.0.8 on 2020-11-22 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0012_consultation_original_idea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='original_idea',
        ),
    ]
