# Generated by Django 3.0.8 on 2020-11-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0013_remove_consultation_original_idea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='stripe_pid',
        ),
    ]
