# Generated by Django 3.0.8 on 2020-11-25 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('consultation', '0014_remove_consultation_stripe_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='profiles.Profile'),
        ),
    ]
