# Generated by Django 3.0.8 on 2020-11-25 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20201125_1725'),
        ('consultation', '0015_consultation_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='profile',
        ),
        migrations.AddField(
            model_name='consultation',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='profiles.UserProfile'),
        ),
    ]
