# Generated by Django 3.0.8 on 2020-11-25 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20201125_1725'),
        ('consultation', '0016_auto_20201125_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation', to='profiles.UserProfile'),
        ),
    ]
